stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/prepare/test.csv
    - data/prepare/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepare/train.csv
    - src/train.py
    params:
    - train.fc2_fc3_n
    - train.epoch
    - train.lr
    outs:
    - models/model.pth
    metrics:
    - metrics/train_metrics.json:
        cache: false
    plots:
    - plots/confusion_matrix.png
    - plots/feature_importance.png
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/prepare/test.csv
    - models/model.pth
    - src/evaluate.py
    outs:
    - metrics/test_metrics.json:
        cache: false
    plots:
    - plots/roc.png
